---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
  namespace: nexvion
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nexvion-postgresql-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: nexvion/prod/postgresql
        property: password
    - secretKey: replication-password
      remoteRef:
        key: nexvion/prod/postgresql
        property: replication-password
    - secretKey: DATABASE_URL
      remoteRef:
        key: nexvion/prod/postgresql
        property: url
    - secretKey: OPENSEARCH_PASSWORD
      remoteRef:
        key: nexvion/prod/opensearch
        property: password
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: nexvion/prod/openai
        property: api-key
