---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-analyzer-secrets
  namespace: nexvion
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nexvion-ai-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENSEARCH_PASSWORD
      remoteRef:
        key: nexvion/prod/ai-analyzer
        property: opensearch-password
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: nexvion/prod/ai-analyzer
        property: openai-api-key
