---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexvion-secrets
  namespace: nexvion
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nexvion-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: nexvion/prod/database
        property: url
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: nexvion/prod/jwt
        property: secret
    - secretKey: OPENSEARCH_PASSWORD
      remoteRef:
        key: nexvion/prod/opensearch
        property: password
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: nexvion/prod/openai
        property: api-key
