{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-backend-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | quote }}
  JWT_SECRET_KEY: {{ .Values.backend.env.JWT_SECRET_KEY | quote }}
{{- end }}