{{- if and .Values.serviceMonitor.enabled (hasKey .Values "monitoring") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-opensearch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-opensearch
  endpoints:
    - port: http
      path: /_prometheus/metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}