---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-slack-token
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
type: Opaque
stringData:
  slack-token: "xoxb-your-slack-bot-token-here"
