---
apiVersion: v1
kind: Secret
metadata:
  name: nexvion-ai-secrets
  labels:
    app.kubernetes.io/name: nexvion
    app.kubernetes.io/component: ai-analyzer
    app.kubernetes.io/part-of: nexvion-ecommerce
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  opensearch-password: "changeme"
  openai-api-key: "changeme"
