---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexvion-postgresql-data
  namespace: nexvion
  labels:
    app.kubernetes.io/name: nexvion
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/part-of: nexvion-ecommerce
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
