---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexvion-secrets
  namespace: nexvion-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nexvion-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: nexvion/dev/database
        property: url
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: nexvion/dev/jwt
        property: secret
    - secretKey: OPENSEARCH_PASSWORD
      remoteRef:
        key: nexvion/dev/opensearch
        property: password
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: nexvion/dev/openai
        property: api-key
